"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from environs import Env
from pathlib import Path
from dotenv import load_dotenv
env = Env()
env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
FACEBOOK_APP_ID = os.getenv('FACEBOOK_APP_ID', default='')
FACEBOOK_APP_SECRET = os.getenv('FACEBOOK_APP_SECRET', default='')
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8da&m*&bly3uv!%fwo!oy-lnazaws0@60$2q*q#^6k)xxp485*'
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', default='')
MIDTRANS_SERVER_KEY = os.getenv("MIDTRANS_SERVER_KEY",default='')
MIDTRANS_CLIENT_KEY = os.getenv("MIDTRANS_CLIENT_KEY",default='')
MIDTRANS_MERCHANT_ID = os.getenv("MIDTRANS_MERCHANT_ID",default='')
MIDTRANS_NOTIFICATION_URL=os.getenv("MIDTRANS_NOTIFICATION_URL",default='')
MIDTRANS_IS_PRODUCTION = env.bool("MIDTRANS_IS_PRODUCTION", default=False)
BITESHIP_API_KEY = os.getenv("BITESHIP_API_KEY", default="").strip()
# Opsional: dipakai integrasi lain / dashboard Biteship (bukan auth Rates API).
BITESHIP_ID_KEY = os.getenv("BITESHIP_ID_KEY", default="").strip()
# Kode pos asal fallback: produk platform (tanpa seller) atau seller belum isi ship_from di profil.
BITESHIP_ORIGIN_POSTAL_CODE = os.getenv("BITESHIP_ORIGIN_POSTAL_CODE", default="12430").strip()
# Daftar kurir Biteship, dipisah koma (lihat dokumentasi Courier API).
BITESHIP_COURIERS = os.getenv("BITESHIP_COURIERS", default="jne,sicepat,tiki").strip()
# Estimasi gram per qty baris keranjang (produk tidak punya berat di DB).
CART_ESTIMATE_WEIGHT_GRAMS_PER_UNIT = int(os.getenv("CART_ESTIMATE_WEIGHT_GRAMS_PER_UNIT", "200"))
# Ongkir checkout bila klien tidak mengirim delivery_fee tervalidasi.
DEFAULT_DELIVERY_FEE = int(os.getenv("DEFAULT_DELIVERY_FEE", "20000"))
# Marketplace seller: komisi platform dari subtotal baris seller (basis poin, 10000 = 100%)
SELLER_PLATFORM_FEE_BPS = int(os.getenv("SELLER_PLATFORM_FEE_BPS", "1000"))

# OpenAI
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# Firebase Admin SDK (FCM push notifications)
FIREBASE_SERVICE_ACCOUNT_JSON = os.getenv("FIREBASE_SERVICE_ACCOUNT_JSON", "")

# Public base URL for building absolute media URLs (set to ngrok/IP when testing on device)
BACKEND_PUBLIC_URL = os.getenv("BACKEND_PUBLIC_URL", "").strip().rstrip("/")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
# Mix Match preview: gpt-image-1.5 multi-image edit (falls back to PIL if disabled or API fails)
MIX_PREVIEW_USE_OPENAI = os.getenv("MIX_PREVIEW_USE_OPENAI", "true").lower() in ("1", "true", "yes")
OPENAI_MIX_PREVIEW_MODEL = os.getenv("OPENAI_MIX_PREVIEW_MODEL", "gpt-image-1.5")
OPENAI_MIX_PREVIEW_SIZE = os.getenv("OPENAI_MIX_PREVIEW_SIZE", "1024x1536")
# Virtual try-on: gpt-image-1.5 images.edit(person + outfit reference(s))
TRYON_USE_OPENAI = os.getenv("TRYON_USE_OPENAI", "true").lower() in ("1", "true", "yes")
OPENAI_TRYON_MODEL = os.getenv("OPENAI_TRYON_MODEL", "gpt-image-1.5")
OPENAI_TRYON_SIZE = os.getenv("OPENAI_TRYON_SIZE", "1024x1536")
# Wardrobe: isolate each detected garment via ``images.edit`` (GPT Image family only).
# Default ``gpt-image-1.5`` matches mix/try-on quality; override with gpt-image-1-mini for lower cost.
WARDROBE_CUTOUT_USE_OPENAI = os.getenv("WARDROBE_CUTOUT_USE_OPENAI", "true").lower() in ("1", "true", "yes")
OPENAI_WARDROBE_CUTOUT_MODEL = os.getenv("OPENAI_WARDROBE_CUTOUT_MODEL", "gpt-image-1.5")
OPENAI_WARDROBE_CUTOUT_SIZE = os.getenv("OPENAI_WARDROBE_CUTOUT_SIZE", "1024x1024")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ALLOW_ALL_ORIGINS = True  # dev only

ALLOWED_HOSTS = ["distichous-demonstratively-guillermo.ngrok-free.dev", "127.0.0.1","localhost"]
CSRF_TRUSTED_ORIGINS = [
    'https://distichous-demonstratively-guillermo.ngrok-free.dev',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'wardrobe',
    'mixmatch',
    'tryon',
    'users',
    'shop',
    'cart',
    'orders',
    'payments',
    'wallet',
    'sellers',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Default SimpleJWT access lifetime is very short (~5 min) — clients that do not
# refresh often hit 401 and feel "logged out". Override via .env if needed.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_MINUTES", "120"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_DAYS", "30"))
    ),
    "ROTATE_REFRESH_TOKENS": False,
}

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
