# Generated by Django 4.2.25 on 2026-04-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('New', 'New'), ('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Dress', 'Dress')], max_length=20)),
                ('image_url', models.ImageField(upload_to='shop/')),
            ],
        ),
    ]
