# Generated by Django 6.0.3 on 2026-04-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixmatch', '0002_mixresult_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixresult',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='mixmatch/previews/%Y/%m/'),
        ),
    ]
