# Generated by Django 6.0.3 on 2026-03-28 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(choices=[('wallet_topup', 'Wallet Top Up')], max_length=30)),
                ('gross_amount', models.PositiveIntegerField()),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Settlement'), ('capture', 'Capture'), ('deny', 'Deny'), ('cancel', 'Cancel'), ('expire', 'Expire'), ('failure', 'Failure'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund')], default='pending', max_length=30)),
                ('fraud_status', models.CharField(blank=True, max_length=30, null=True)),
                ('snap_token', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
