// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGpixte-HrR_7GsIcUrfYTcq8fXEE-Kvc',
    appId: '1:75070881856:web:1906b0d567ed50d9075fa5',
    messagingSenderId: '75070881856',
    projectId: 'mixera-b0085',
    authDomain: 'mixera-b0085.firebaseapp.com',
    storageBucket: 'mixera-b0085.firebasestorage.app',
    measurementId: 'G-NKBEC3316B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuhAwp_xQwYMSYw5hPaIcfK-bl2NiFrUc',
    appId: '1:75070881856:android:f94440615629604e075fa5',
    messagingSenderId: '75070881856',
    projectId: 'mixera-b0085',
    storageBucket: 'mixera-b0085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0QZ_fWpv6xm9KbgKd9ooGgXTiRwTvXc',
    appId: '1:75070881856:ios:c72022062c530be6075fa5',
    messagingSenderId: '75070881856',
    projectId: 'mixera-b0085',
    storageBucket: 'mixera-b0085.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0QZ_fWpv6xm9KbgKd9ooGgXTiRwTvXc',
    appId: '1:75070881856:ios:c72022062c530be6075fa5',
    messagingSenderId: '75070881856',
    projectId: 'mixera-b0085',
    storageBucket: 'mixera-b0085.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGpixte-HrR_7GsIcUrfYTcq8fXEE-Kvc',
    appId: '1:75070881856:web:30cb859e4da0e96f075fa5',
    messagingSenderId: '75070881856',
    projectId: 'mixera-b0085',
    authDomain: 'mixera-b0085.firebaseapp.com',
    storageBucket: 'mixera-b0085.firebasestorage.app',
    measurementId: 'G-ZW2WYCCDRM',
  );
}
