# Generated by Django 6.0.3 on 2026-03-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notificationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='app_updates',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='daily_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='security_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
