# Generated by Django 6.0.3 on 2026-04-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('tryon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonrequest',
            name='shop_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tryon_requests', to='shop.product'),
        ),
        migrations.AddField(
            model_name='tryonrequest',
            name='source_type',
            field=models.CharField(choices=[('mix_result', 'Mix Result'), ('shop_product', 'Shop Product')], default='mix_result', max_length=20),
        ),
    ]
