# Generated by Django 6.0.3 on 2026-04-07 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixmatch', '0002_mixresult_tips'),
        ('shop', '0001_initial'),
        ('tryon', '0002_tryonrequest_shop_product_tryonrequest_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tryonresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tryonrequest',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='tryonrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mix_result__isnull', False), ('shop_product__isnull', True), ('source_type', 'mix_result')), models.Q(('mix_result__isnull', True), ('shop_product__isnull', False), ('source_type', 'shop_product')), _connector='OR'), name='tryonrequest_valid_mix_result_source'),
        ),
    ]
