# Generated by Django 6.0.3 on 2026-04-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0003_alter_tryonresult_options_tryonrequest_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonresult',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False, help_text='User favourite — shown in saved try-on section.'),
        ),
    ]
