# Generated by Django 6.0.3 on 2026-04-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0005_personprofileimage_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofileimage',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-hide from library; kept so TryOnRequest.person_image (PROTECT) stays valid.'),
        ),
    ]
