# Generated by Django 4.2.29 on 2026-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('outer', 'Outer'), ('top', 'Top'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('shoes', 'Shoes'), ('dresses', 'Dresses')], max_length=255)),
                ('favorite', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to=None, verbose_name='Image')),
            ],
        ),
    ]
