# Generated by Django 6.0.3 on 2026-04-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
